### ISSUE TITLE
Landingpage Home

### ISSUE THREAD

**Issue by Wizzard26** [Wizzard26/capstone-project#2]
## Display Home page

As a User
I want to see a teaser with information
about the site and the functions

## Description
![Landingpage](https://user-images.githubusercontent.com/40913589/234328474-8e1cf9d8-5f61-437c-aa94-8140cc1ce918.png)

## Acceptance criteria

- [ ] Show a teaser image
- [ ] Show teaser text with informations

## Tasks

- [ ] Create image component
- [ ] Add teaser Image
- [ ] Add teaser text

**Comment by BenRodProd** [comment]
Looks good, but how does the User get to the Player list from here (us1). Is there a Button that links to it?
