### ISSUE TITLE
Header and Footer Navigation

### ISSUE THREAD

**Issue by Wizzard26** [Wizzard26/capstone-project#3]
## Display Header and Footer Navigation

As a User
I want to navigate between the different 
sites of the page

## Description

![Navigation](https://user-images.githubusercontent.com/40913589/234378497-f65055cd-521f-4de5-b423-17aa2c11f0ba.png)

## Acceptance criteria

- [ ] Header Logo with link to root page
- [ ] Header burgernavigation with collapse navigation
- [ ] Footer Button link to Players list
- [ ] Footer Button link to favorites list

## Tasks

- [ ] Create a topbar for header
- [ ] Add Logo with link to topbar
- [ ] Add burgernavigation to topbar
- [ ] Create Footer button component
- [ ] Add Players list button to footer
- [ ] add Favorites list button to footer
