### ISSUE TITLE
Player Details Page

### ISSUE THREAD

**Issue by Wizzard26** [Wizzard26/capstone-project#5]
## Display Player Details

As a User
I want to see
the details of a single player

## Description

![PlayerDetails](https://user-images.githubusercontent.com/40913589/234381087-094ad43d-7728-42d1-bc87-6696c767c32f.png)

## Acceptance criteria

- [ ] Show player name as headline
- [ ] Show player Image
- [ ] Show teaser text of the player
- [ ] List detail information from player
- [ ] List titles and other sporting achievements

## Tasks

- [ ] Add image component with player image
- [ ] Add teaser comonent with player information
- [ ] Create details table component
- [ ] Add player details to table
- [ ] Create achievment list
- [ ] Add achievment list
